update readme
covidwatchorg/covidwatch-android-en pull request #50
Opened 2020-05-20 20:45 UTC by crayne

2020-05-21 15:24 UTC, Apisov requested changes

2020-05-21 15:24 UTC, Apisov commented on README.md
>  git clone git@github.com:covid19risk/covidwatch-android.git
it's `covidwatch-android-en` in this repo

2020-05-21 15:24 UTC, Apisov commented on README.md
> -- Look at https://github.com/orgs/covid19risk/projects/1 for existing issues. If you see something you want to work on, assign yourself to it, set it to in progress, and make a PR to the `develop` br
https://github.com/orgs/covid19risk/projects/1 is our project for this repo as well

2020-05-21 15:24 UTC, Apisov commented on README.md
> +- Look at https://blog.google/documents/68/Android_Exposure_Notification_API_documentation_v1.2.pdf for existing issues. If you see something you want to work on, assign yourself to it, set it to in
That PDF doesn't show issues in our application. Please return previous item with link to the GitHub project.

2020-05-21 15:24 UTC, Apisov commented on README.md
> +Covid Watch uses Google/Android Exposure Notification, a decentralized, privacy-first contact tracing API implemented in Google and Apple phone operation systems. You can read more about it in the Go
This PDF gets updates from time to time so it will more safe to give a link to the overview:
https://www.google.com/covid19/exposurenotifications/

2020-05-21 17:56 UTC, crayne commented on README.md
>  git clone git@github.com:covid19risk/covidwatch-android.git
Done

2020-05-21 18:12 UTC, crayne commented
Ready for review

2020-05-21 22:53 UTC, crayne commented
Thank you, I received it.
Susan
    On Thursday, May 21, 2020, 11:24:26 AM EDT, Apisov <notifications@github.com> wrote:  
 
 


@Apisov requested changes on this pull request.

In README.md:
>  
 ## Setup
 
 Clone this repo from the `develop` branch:
 
-```
 git clone git@github.com:covid19risk/covidwatch-android.git

it's covidwatch-android-en in this repo

In README.md:
>  
 Open the project in Android Studio. Install onto a phone of yours with the `app` configuration, and you're free to explore the app! Its optimal to install on 2 phones as much of the behavior of the app depends on 2 phones interacting.
 
 **Note:** You cannot run this app on an emulator! We are dependent on Bluetooth being on and active, and most standard Android emulators do not have Bluetooth drivers.
 
 ## Looking to contribute?
 
-- Run on your own device to explore the UX. Look at the [Figma](https://www.figma.com/file/0uL6s79o21jwUFZz16Dr8b/Covid-Watch---App-v1.8?node-id=0%3A1) for what the UX should look like. If you have any feedback/find any problems, create an issue!
-- Look at https://github.com/orgs/covid19risk/projects/1 for existing issues. If you see something you want to work on, assign yourself to it, set it to in progress, and make a PR to the `develop` branch.

https://github.com/orgs/covid19risk/projects/1 is our project for this repo as well

In README.md:
>  
 Open the project in Android Studio. Install onto a phone of yours with the `app` configuration, and you're free to explore the app! Its optimal to install on 2 phones as much of the behavior of the app depends on 2 phones interacting.
 
 **Note:** You cannot run this app on an emulator! We are dependent on Bluetooth being on and active, and most standard Android emulators do not have Bluetooth drivers.
 
 ## Looking to contribute?
 
-- Run on your own device to explore the UX. Look at the [Figma](https://www.figma.com/file/0uL6s79o21jwUFZz16Dr8b/Covid-Watch---App-v1.8?node-id=0%3A1) for what the UX should look like. If you have any feedback/find any problems, create an issue!
-- Look at https://github.com/orgs/covid19risk/projects/1 for existing issues. If you see something you want to work on, assign yourself to it, set it to in progress, and make a PR to the `develop` branch.
+- Run on your own device to explore the UX. Look at the [Figma](https://www.figma.com/file/I4OOjT4VhsSberDIAZTkcH/Covid-Watch---App-v2-(dev)?node-id=0%3A1) for what the UX should look like. If you have any feedback/find any problems, create an issue!
+- Look at https://blog.google/documents/68/Android_Exposure_Notification_API_documentation_v1.2.pdf for existing issues. If you see something you want to work on, assign yourself to it, set it to in progress, and make a PR to the `develop` branch.

That PDF doesn't show issues in our application. Please return previous item with link to the GitHub project.

In README.md:
>  
 ## FAQ
 
 What is the anonymous protocol for communication between phones? How does it work and who designed it?
 
-Covid Watch uses Temporary Contact Numbers, a decentralized, privacy-first contact tracing protocol developed by the [TCN Coalition](https://tcn-coalition.org/). This protocol is built to be extensible, with the goal of providing interoperability between contact tracing applications. You can read more about it on their [Github](https://github.com/TCNCoalition/TCN).
+Covid Watch uses Google/Android Exposure Notification, a decentralized, privacy-first contact tracing API implemented in Google and Apple phone operation systems. You can read more about it in the Google design document at https://blog.google/documents/68/Android_Exposure_Notification_API_documentation_v1.3.1.pdf

This PDF gets updates from time to time so it will more safe to give a link to the overview:
https://www.google.com/covid19/exposurenotifications/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-05-22 18:11 UTC, Apisov approved these changes

2020-05-22 18:11 UTC, merged