Add share sheet action to share app button
covidwatchorg/covidwatch-android-en pull request #53
Opened 2020-05-24 22:38 UTC by redbassett

2020-05-25 16:22 UTC, Apisov requested changes

2020-05-25 16:22 UTC, Apisov commented on app/src/main/java/org/covidwatch/android/ui/util/ShareApp.kt
> +fun Context.shareApp() {
Could you please move this flie into `org.covidwatch.android.extension` package and rename it as `Context`?

2020-05-25 16:40 UTC, redbassett commented
Changes made.

2020-05-26 15:27 UTC, Apisov approved these changes

2020-05-26 15:28 UTC, merged